version: '3.7'
services:
  node_container:
    build: .
    command: node server.js
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
    - "3000:3000"
    depends_on:
    - mongodb_container
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    logging:
      driver: "none"

volumes:
  mongodb_data_container:
